- name: Disable firewall on Ubuntu
  hosts: k3s
  become: true
  gather_facts: true
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Disable UFW
      community.general.ufw:
        state: disabled
