- name: Install k3s
  hosts: lxc
  vars:
    ansible_host_key_checking: false
  become: true
  tasks:
    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /usr/local/bin/k3s-install.sh
        mode: '0755'
      register: dl

    - name: Confirm download
      ansible.builtin.debug:
        msg: "Successfully downloaded k3s installer"
      when: dl.changed

    - name: Run k3s installer
      ansible.builtin.shell: /usr/local/bin/k3s-install.sh
      args:
        executable: /bin/sh
      register: run

    - name: Confirm install
      ansible.builtin.debug:
        msg: "Successfully installed k3s"
      when: run.rc == 0
