# uninstall-k3s.yml
- name: Uninstall k3s
  hosts: k3s
  become: true
  tasks:
    - name: Check for server uninstaller
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-uninstall.sh
      register: k3s_srv

    - name: Check for agent uninstaller
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: k3s_agent

    - name: Run server uninstaller
      ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh
      args:
        executable: /bin/bash
      when: k3s_srv.stat.exists

    - name: Run agent uninstaller
      ansible.builtin.shell: /usr/local/bin/k3s-agent-uninstall.sh
      args:
        executable: /bin/bash
      when: k3s_agent.stat.exists
