version: "3.9"

# BACKUP COMPOSE FILE - Media Apps for Docker fallback
# Use this if you need to temporarily move media apps back to Docker

networks:
  proxy:
    external: true

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr-backup
    networks: [proxy]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/appdata/radarr-backup:/config
      - /mnt/nas/media/Downloads:/downloads
      - /mnt/nas/media/Movies:/movies
    restart: unless-stopped
    expose: ["7878"]

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr-backup
    networks: [proxy]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/appdata/sonarr-backup:/config
      - /mnt/nas/media/Downloads:/downloads
      - /mnt/nas/media/TV:/tv
    restart: unless-stopped
    expose: ["8989"]

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr-backup
    networks: [proxy]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/appdata/lidarr-backup:/config
      - /mnt/nas/media/Downloads:/downloads
      - /mnt/nas/media/Music:/music
    restart: unless-stopped
    expose: ["8686"]

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr-backup
    networks: [proxy]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/appdata/prowlarr-backup:/config
    restart: unless-stopped
    expose: ["9696"]

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-backup
    networks: [proxy]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /opt/appdata/qbittorrent-backup:/config
      - /mnt/nas/media/Downloads:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    expose: ["8080"]

  overseerr:
    image: lscr.io/linuxserver/overseerr:develop
    container_name: overseerr-backup
    networks: [proxy]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/appdata/overseerr-backup:/config
      - /mnt/nas/media/Movies:/movies
      - /mnt/nas/media/TV:/shows
      - /mnt/nas/media/Downloads:/downloads
    restart: unless-stopped
    expose: ["5055"]
