# validate-cluster.yml
# Comprehensive validation of K3s cluster and applications

- name: Validate K3s Cluster
  hosts: k3s_servers[0]
  become: true
  tasks:
    - name: Check cluster nodes
      ansible.builtin.command: kubectl get nodes --no-headers
      register: nodes_status
      changed_when: false

    - name: Verify all nodes are Ready
      ansible.builtin.shell: kubectl get nodes --no-headers | grep -v Ready | wc -l
      register: unready_nodes
      changed_when: false
      failed_when: unready_nodes.stdout | int > 0

    - name: Display node status
      ansible.builtin.debug:
        var: nodes_status.stdout_lines

    - name: Check system pods
      ansible.builtin.command: kubectl get pods -n kube-system
      register: system_pods
      changed_when: false

    - name: Verify system pods are running
      ansible.builtin.shell: kubectl get pods -n kube-system --no-headers | grep -v Running | grep -v Completed | wc -l
      register: failed_system_pods
      changed_when: false
      failed_when: failed_system_pods.stdout | int > 0

    - name: Display system pods
      ansible.builtin.debug:
        var: system_pods.stdout_lines

    - name: Check Traefik service
      ansible.builtin.command: kubectl get svc -n traefik
      register: traefik_svc
      changed_when: false
      failed_when: false

    - name: Display Traefik service
      ansible.builtin.debug:
        var: traefik_svc.stdout_lines
      when: traefik_svc.rc == 0

    - name: Check resource usage
      ansible.builtin.command: kubectl top nodes
      register: resource_usage
      changed_when: false
      failed_when: false

    - name: Display resource usage
      ansible.builtin.debug:
        var: resource_usage.stdout_lines
      when: resource_usage.rc == 0

    - name: Test DNS resolution
      ansible.builtin.command: kubectl run test-dns --image=busybox --rm -it --restart=Never -- nslookup kubernetes.default
      register: dns_test
      changed_when: false
      failed_when: false

    - name: Check ArgoCD if installed
      ansible.builtin.command: kubectl get pods -n argocd
      register: argocd_pods
      changed_when: false
      failed_when: false

    - name: Display ArgoCD status
      ansible.builtin.debug:
        var: argocd_pods.stdout_lines
      when: argocd_pods.rc == 0

    - name: Validation summary
      ansible.builtin.debug:
        msg:
          - "========================================="
          - "Cluster Validation Complete!"
          - "========================================="
          - "Nodes: {{ nodes_status.stdout_lines | length }}"
          - "All nodes ready: {{ unready_nodes.stdout | int == 0 }}"
          - "System pods healthy: {{ failed_system_pods.stdout | int == 0 }}"
          - ""
          - "Next steps:"
          - "1. Deploy ArgoCD: ansible-playbook applications/bootstrap-argocd.yml"
          - "2. Deploy applications via ArgoCD"
          - "3. Configure nginx-proxy-manager to route to Traefik"

